[dev]
  command = "npm start"
  targetPort = 4200
  autoLaunch = false

[build]
  command = "npm run build"
  publish = "dist/ddc/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

